@extends('layouts.app')
@section('title','Inicio')
@section('content')
<div class="app-page-header"><div><h1>Inicio</h1><p>Resumen de tu biblioteca musical.</p></div><div class="app-page-actions"><a class="btn btn-primary" href="{{ route('songs.create') }}"><i class="bi bi-plus-lg"></i>Nueva canción</a><a class="btn btn-outline-primary" href="{{ route('repertoires.create') }}"><i class="bi bi-list-ol"></i>Crear repertorio</a></div></div>
<div class="row g-3 mb-4"><div class="col-sm-6"><div class="card metric-card h-100"><div class="card-body"><span class="text-secondary">Canciones</span><div class="display-6 fw-semibold">{{ $songCount }}</div></div></div></div><div class="col-sm-6"><div class="card metric-card h-100"><div class="card-body"><span class="text-secondary">Repertorios</span><div class="display-6 fw-semibold">{{ $repertoireCount }}</div></div></div></div></div>
<div class="row g-4">
<div class="col-lg-6"><div class="card h-100"><div class="card-header app-section-header"><h2>Últimas canciones</h2></div><div class="list-group list-group-flush">@forelse($latestSongs as $song)<a class="list-group-item list-group-item-action py-3" href="{{ route('songs.show',$song) }}"><strong>{{ $song->title }}</strong><small class="d-block text-secondary">{{ $song->author ?: 'Autor no indicado' }}</small></a>@empty<div class="app-empty-state py-4"><i class="bi bi-music-note"></i>Aún no hay canciones.</div>@endforelse</div></div></div>
<div class="col-lg-6"><div class="card h-100"><div class="card-header app-section-header"><h2>Repertorios recientes</h2></div><div class="list-group list-group-flush">@forelse($recentRepertoires as $repertoire)<a class="list-group-item list-group-item-action py-3" href="{{ route('repertoires.show',$repertoire) }}"><strong>{{ $repertoire->name }}</strong><small class="d-block text-secondary">{{ $repertoire->event_date?->format('d-m-Y') ?: 'Sin fecha' }}</small></a>@empty<div class="app-empty-state py-4"><i class="bi bi-list-ol"></i>Aún no hay repertorios.</div>@endforelse</div></div></div>
<div class="col-lg-8"><div class="card h-100"><div class="card-header app-section-header"><h2>Próximos eventos</h2></div><div class="list-group list-group-flush">@forelse($upcomingRepertoires as $repertoire)<a class="list-group-item list-group-item-action d-flex justify-content-between gap-3 py-3" href="{{ route('repertoires.show',$repertoire) }}"><span class="fw-semibold">{{ $repertoire->name }}</span><span class="text-secondary text-nowrap">{{ $repertoire->event_date->format('d-m-Y') }}</span></a>@empty<div class="app-empty-state py-4"><i class="bi bi-calendar3"></i>No hay próximos eventos.</div>@endforelse</div></div></div>
<div class="col-lg-4"><div class="card h-100"><div class="card-header app-section-header"><h2>Último repertorio</h2></div><div class="card-body">@if($lastRepertoire)<h3 class="h5"><a class="app-list-link" href="{{ route('repertoires.show',$lastRepertoire) }}">{{ $lastRepertoire->name }}</a></h3><span class="badge {{ $lastRepertoire->status === 'ready' ? 'text-bg-success' : ($lastRepertoire->status === 'archived' ? 'text-bg-secondary' : 'text-bg-warning') }}">{{ ['draft'=>'Borrador','ready'=>'Listo','archived'=>'Archivado'][$lastRepertoire->status] }}</span>@else<div class="app-empty-state p-3"><i class="bi bi-list-ol"></i>Sin repertorios disponibles.</div>@endif</div></div></div>
</div>
@endsection