@extends('layouts.app')
@section('title', $definition['title'])
@section('content')
<div class="app-page-header"><div><a class="small text-decoration-none" href="{{ route('admin.settings') }}"><i class="bi bi-arrow-left"></i> Configuración</a><h1 class="mt-2">{{ $definition['title'] }}</h1><p>{{ $definition['description'] }}</p></div></div>
<div class="row g-4 align-items-start">
<div class="col-lg-4"><div class="card"><div class="card-body"><h2 class="h5 mb-3">Agregar {{ $definition['singular'] }}</h2><form method="POST" action="{{ route('admin.catalogs.store', $catalog) }}">@csrf
<div class="mb-3"><label class="form-label" for="new-name">Nombre</label><input class="form-control" id="new-name" name="name" value="{{ old('name') }}" required maxlength="255"></div>
<div class="mb-3"><label class="form-label" for="new-slug">Slug <span class="text-secondary fw-normal">(opcional)</span></label><input class="form-control" id="new-slug" name="slug" value="{{ old('slug') }}" maxlength="255"><div class="form-text">Si se deja vacío, se genera desde el nombre.</div></div>
<div class="mb-3"><label class="form-label" for="new-description">Descripción</label><textarea class="form-control" id="new-description" name="description" rows="3" maxlength="2000">{{ old('description') }}</textarea></div>
<div class="mb-3"><label class="form-label" for="new-order">Orden</label><input class="form-control" id="new-order" type="number" min="0" name="sort_order" value="{{ old('sort_order', 0) }}" required></div>
<input type="hidden" name="is_active" value="1"><button class="btn btn-primary w-100" type="submit"><i class="bi bi-plus-lg"></i>Agregar</button></form></div></div></div>
<div class="col-lg-8"><div class="d-grid gap-3">@forelse($items as $item)
<form class="card" method="POST" action="{{ route('admin.catalogs.update', [$catalog, $item]) }}">@csrf @method('PUT')<div class="card-body"><div class="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-3"><div><strong>{{ $item->name }}</strong><span class="badge {{ $item->is_active ? 'text-bg-success' : 'text-bg-secondary' }} ms-2">{{ $item->is_active ? 'Activa' : 'Inactiva' }}</span></div><small class="text-secondary">{{ $item->songs_count }} {{ $item->songs_count === 1 ? 'canción asociada' : 'canciones asociadas' }}</small></div>
<div class="row g-3"><div class="col-md-7"><label class="form-label" for="name-{{ $item->id }}">Nombre</label><input class="form-control" id="name-{{ $item->id }}" name="name" value="{{ $item->name }}" required maxlength="255"></div><div class="col-md-5"><label class="form-label" for="slug-{{ $item->id }}">Slug</label><input class="form-control" id="slug-{{ $item->id }}" name="slug" value="{{ $item->slug }}" maxlength="255"></div><div class="col-12"><label class="form-label" for="description-{{ $item->id }}">Descripción</label><textarea class="form-control" id="description-{{ $item->id }}" name="description" rows="2" maxlength="2000">{{ $item->description }}</textarea></div><div class="col-sm-4"><label class="form-label" for="order-{{ $item->id }}">Orden</label><input class="form-control" id="order-{{ $item->id }}" type="number" min="0" name="sort_order" value="{{ $item->sort_order }}" required></div><div class="col-sm-8 d-flex flex-wrap align-items-end justify-content-sm-end gap-2"><input type="hidden" name="is_active" value="0"><div class="form-check form-switch mb-2"><input class="form-check-input" id="active-{{ $item->id }}" type="checkbox" name="is_active" value="1" @checked($item->is_active)><label class="form-check-label" for="active-{{ $item->id }}">Disponible en formularios</label></div><button class="btn btn-outline-primary" type="submit"><i class="bi bi-check-lg"></i>Guardar</button></div></div></div></form>
@empty<div class="card"><div class="app-empty-state"><i class="bi bi-inboxes"></i><h2 class="h5">No hay opciones configuradas</h2><p class="mb-0">Agrega la primera opción desde el formulario.</p></div></div>@endforelse</div></div>
</div>
@endsection